### ISSUE TITLE
Plugin won't start because of missing files

### ISSUE THREAD

**Issue by danielpetrovic** [Ff00ff/homebridge-duco#1]
**Describe The Bug:**
Plugin won't start, see below.

**To Reproduce:**
Download master.zip and unzip into Homebridge plugins folder.

Also tried install with: sudo hb-service add https://github.com/Ff00ff/homebridge-duco and the error is the same (apart from different path).

**Expected behavior:**
It should start.

**Logs:**
====================
ERROR LOADING PLUGIN homebridge-plugin-duco:
Error: Cannot find module '/var/lib/homebridge/node_modules/homebridge-duco/dist/index.js'
Require stack:
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/var/lib/homebridge/node_modules/homebridge/src/pluginManager.ts:141:22)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:173:30)

**Plugin Config:**
Nothing configured yet for this plugin, as the plugin is not starting yet and the README doesn't contain what values are expected, if there are any.

**Environment:**

* **Plugin Version**: 1.0.0
* **Homebridge Version**: 1.5.0.
* **Node.js Version**: v16.15.1
* **NPM Version**: 7.5.2
* **Operating System**: Raspbian 11

**Comment by danielpetrovic** [comment]
So, I did some digging as I saw you used the template plugin as a start and I started work on another plugin.

When I run the following the plugin will start and does something, sadly it cannot find my Duco unit on the network.

cd /var/lib/homebridge/node_modules/
git clone https://github.com/Ff00ff/homebridge-duco.git
cd homebridge-duco/
npm install
npm build run

The dependencies and built plugin are missing from your GitHub repo, which cause the dependencies error.

I added the following to my config:
`        {
            "name": "Duco",
            "platform": "Duco"
        },`

Now I just get:
[7/31/2022, 12:39:56 AM] [Duco] Could not find any DUCO instance on your local network. Going to retry in 30 seconds.
[7/31/2022, 12:40:26 AM] [Duco] Searching for DUCO instance
[7/31/2022, 12:40:46 AM] [Duco] Could not find any DUCO instance on your local network. Going to retry in 30 seconds.
[7/31/2022, 12:41:16 AM] [Duco] Searching for DUCO instance
[7/31/2022, 12:41:36 AM] [Duco] Could not find any DUCO instance on your local network. Going to retry in 30 seconds.
[7/31/2022, 12:42:06 AM] [Duco] Searching for DUCO instance
[7/31/2022, 12:42:26 AM] [Duco] Could not find any DUCO instance on your local network. Going to retry in 30 seconds.
[7/31/2022, 12:42:56 AM] [Duco] Searching for DUCO instance

**Comment by wimleers** [comment]
Thanks for the pointers, @danielpetrovic, that helped me get this going in minutes!

@martijndeh Any plans to make this more feature-complete? For example, CO2 levels are currently not exposed. And there's excessive non-debug logging like this:
```
[10/4/2022, 7:36:11 PM] [Ducobox Focus] [duco001.local#1] Ventilation level is still AUTO
[10/4/2022, 7:36:15 PM] [Ducobox Focus] [duco001.local#3] Ventilation level is still AUTO
[10/4/2022, 7:36:28 PM] [Ducobox Focus] [duco001.local#4] Ventilation level is still AUTO
[10/4/2022, 7:36:29 PM] [Ducobox Focus] [duco001.local#2] Ventilation level is still AUTO
[10/4/2022, 7:36:33 PM] [Ducobox Focus] [duco001.local#5] Ventilation level is still AUTO
[10/4/2022, 7:36:38 PM] [Ducobox Focus] [duco001.local#6] Ventilation level is still AUTO
[10/4/2022, 7:36:59 PM] [Ducobox Focus] [duco001.local#144] Ventilation level is still AUTO
```
Furthermore, these accessories could use the `location` field associated with each Ducobox `node`; that would result in something much more useful than this:
<img width="504" alt="Screen Shot 2022-10-04 at 19 40 33" src="https://user-images.githubusercontent.com/14240/193888784-e45d005d-bb54-4360-9964-b34218d2f096.png">

In any case: THANK YOU to get this going so far already! 👍 🙏

**Comment by wimleers** [comment]
Due to the lack of response here, I decided to fork this repo and move this forward — see https://github.com/wimleers/homebridge-ducobox.
